version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  BeforeInstall:
    - location: install_docker.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: build_docker_image.sh
      timeout: 300
      runas: root
